info:
  tasks: gsm8k
  type: math
  default_eval_type: generation

data:
  repo_type: hf
  path: openai/gsm8k
  subset: main
  split: test
  question_column: 
    - question
  answer_column: 
    - answer 
  only_answer: false
